---
- name: "creating ec2 instance"
  ec2:
    key_name: "{{ key_pair }}"
    instance_type: "{{ instance_size }}"
    region: us-west-2
    image: "{{ ami_id }}"
    wait: yes
    group: "{{ sg_name }}"
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ instance_name }}"
      Stack: "{{ stack_name }}"
    exact_count: 1
    count_tag:
      Name: "{{ instance_name }}"
  register: ec2
#- debug: msg= "{{ ec2.tagged_instances.item.public_ip }}"

- name: Add new instance to host group
  local_action: lineinfile
                dest="./hosts"
                regexp={{ item.public_ip }}
                insertafter="[launched]" line="{{ item.public_ip }} ansible_ssh_user=ubuntu  instance_id={{ item.id }} ansible_ssh_private_key_file=/home/ubuntu/{{ key_pair }}.pem"
  with_items: ec2.tagged_instances

- name: Wait for SSH
  local_action: wait_for
                host={{ item.public_ip }}
                port=22
                state=started
  with_items: ec2.tagged_instances
