---
- include_vars: /root/ansible/vars/main.yml
- name: creating AMI
  ec2_ami:
    wait: yes
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secreate_key }}"
    region: "{{ region }}"
    instance_id: "{{ instance_id }}"
    name: "{{ aminame }}"
  register: image
