---
- hosts: localhost
  connection: local
  gather_facts: True
  vars:
  vars_files:
    - ["vars/main.yml"]
  roles:
    - role: aws-launch-instance

- hosts: launched

  roles: 
    - role: common
    - role: jetty
    - role: create-ami
